### PR TITLE
Add test to check if chained encoders finishes

### PR DESCRIPTION
**Pull request by marcospb19**

### CODE REVIEW

**Comment by marcospb19** [comment]
Hey, I do believe this test should pass, but it hangs indefinitely.

This is a minimal test of another test that I was doing, involving chaining encoders and decoders.

The test chains 5 `Encoders` and writes on the top one, the result should be random data in the format `.bz3.bz3.bz3.bz3.bz3`, but it just hangs.

**Comment by marcospb19** [comment]
Related to #1, in Ouch it's possible to chain any number of formats when compressing or decompressing a file/archive.

**Comment by bczhc** [comment]
Good catch! This is a bug! Thanks for finding it. I'm on the way fixing them... For the tests, I hope `{read, write}::{Bz3Encoder, Bz3Decoder}` with a variety of `block_size` can all be covered. Now your 5 chained encoder test can pass. I'm working to fix and test another three cases.

**Comment by bczhc** [comment]
e2ed1991d55e7eb4f46063b3ab5207bf1901cdc9. all chained cases seem to be OK. I use an `eof` flag to solve this, just not coming up with a more elegant approach...

**Comment by marcospb19** [comment]
For reference, here is [the original test I wrote](https://github.com/bczhc/bzip3-rs/compare/master...marcospb19:bzip3-rs:joao/ideal-test), it chains write decoders with read encoders.

Do you want to commit the tests yourself? Otherwise I can edit this PR and try merging one of the two tests I've shown you, Whatever you prefer, let me know :pray:.

(Your responses are lightning quick :zap::zap::zap:, no need to rush though!)

**Comment by marcospb19** [comment]
Oh, note that I set the random-data length to be bigger than the block size, that's to force `Bz3Encoder`s to make multiple reads, if length was less than block size, I believe a single read for each item in the chain would be enough, but I wanted to test the "interleaving" calls of Read between the encoders, going back and forth.

I used:
```rust
block size = 70kb
random data length = 200kb
```

One thing I just realized is that only the first one might be forced to write it all, because compressed data is shrunk down.

```
200KB -> ReadEncoder1 (reads 200KB) -> ReadEncoder2 (reads X) -> ReadEncoder3 (reads Y)
```

If X and Y are below 70kb, then it's a single-block read, so we might have to do some tests and raise the random data length.

Maybe having two different tests... one with smaller input for single-block processing, and one with bigger input for multi-block processing.

**Comment by marcospb19** [comment]
Oops forgot to rebase.

**Comment by bczhc** [comment]
Oh great! LGTM, thanks!

**Comment by marcospb19** [comment]
With this merged I think I can go back to the Ouch side, I was getting a bug with chained formats and I think that was the cause.

**Pull request merged**
